# https://github.com/actions/labeler/#match-object

config:
  - any:
    - changed-files:
      - any-glob-to-any-file: [
          '.eleventy.config.images.js',
          '.eleventy.js',
          '.eleventyignore',
          '.gitignore',
        ]

post:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['posts/*/*.md']

image:
  - any:
    - changed-files:
      - any-glob-to-any-file: [
          'posts/*/*.jpg',
          'posts/*/*.png',
        ]

format:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['**/*.njk']

GitHub:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['.github/*']