# https://github.com/actions/labeler/#match-object

config:
  - any:
    - '.eleventy.config.images.js'
    - '.eleventy.js'
    - '.eleventyignore'
    - '.gitignore'

post:
  - any:
    - 'posts/*'

image:
  - any:
    - 'posts/*/*.jpg'
    - 'posts/*/*.png'

format:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['**/*.njk']

GitHub:
  - any:
    - changed-files:
      - any-glob-to-any-file: ['.github/*']